feature/WIK 100 password reset backend
tunapanda/wikonnect pull request #649
Opened 2021-03-25 09:38 UTC by mosesokemwa

- endpoints for resetting passwords
- Co-authored-by: Brian Marete <brianmarete@users.noreply.github.com>

- [x] I have read [Wikonnects contributing guidelines](https://github.com/tunapanda/wikonnect/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request passes all tests.

Closes #638

### Change Log

2021-04-01 09:19 UTC, brianmarete approved these changes

2021-04-23 13:07 UTC, mimidotsuser requested changes

2021-04-23 13:07 UTC, mimidotsuser commented on server/routes/users.js
> +  let user = await User.query().findOne({ 'email': decodedMail });
someone can easily bypass verification by making an API request to this endpoint with email query parameter e.g. `/api/v1/users/${randomId}/verify?email=${base64EncodedEmail}`

the endpoint should verify that the token received is associated to the user email first.

2021-04-23 13:07 UTC, mimidotsuser commented on server/routes/users.js
>      if (new Date() < user.resetPasswordExpires) {
throw an error if the request has expired. With current flow, the endpoint will return 200 ok status

2021-04-28 13:18 UTC, mimidotsuser approved these changes

2021-04-28 15:38 UTC, mimidotsuser commented
@brianmarete just noticed `resetPasswordToken` & `resetPasswordExpires`  properties are returned on `api/v1/users/` endpoints. I think we should not expose this to anyone{even to an admin}

2021-04-29 09:02 UTC, mosesokemwa commented
> since this PR does away with Redis, this should also be updated on the readme.md.
> 
> Instructions on how to set up the mail configuration should also be included

This was already accounted for in the docs

2021-04-29 09:05 UTC, mosesokemwa commented
> @brianmarete just noticed `resetPasswordToken` & `resetPasswordExpires` properties are returned on `api/v1/users/` endpoints. I think we should not expose this to anyone{even to an admin}

@brianmarete I added the attributes to secure field attributes in the model file, they will not be exposed

2021-05-03 12:31 UTC, merged